package com.germplasm.dao;

import com.germplasm.model.BiologyInfo;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface BiologyInfoMapper {
    @Delete({
        "delete from biology_info",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    @Insert({
        "insert into biology_info (id, germ_id, ",
        "sprout_ability, branch_ability, ",
        "branch_aver_length, growtch, ",
        "first_fruit_age, acme_fruit_age, ",
        "long_branch_ratio, mid_branch_ratio, ",
        "short_branch_ratio, axi_bud_ratio, ",
        "phy_fruit_drop, before_fruit_drop, ",
        "single_aver_yield, single_max_yield, ",
        "unit_yield, yeild_descript, ",
        "germ_stage, flower_stage, ",
        "harvest_stage, leaffall_stage, ",
        "storage, diseases, ",
        "pest, cold_resistance, ",
        "drougth_resistance, wind_resistance, ",
        "water_resistance, soil_adaptive, ",
        "climate_adaptive, planting_condition, ",
        "fruit_long_diameter, fruit_lat_diameter, ",
        "single_fruit_weight, fruit_shape, ",
        "fruit_color, fruit_skin, ",
        "fruit_wax, fruit_dots, ",
        "fruit_stem, fruit_hollow, ",
        "fruit_sepal, fruit_depression, ",
        "flesh_color, flesh_texture, ",
        "flesh_type, flesh_stone_cell, ",
        "flesh_juice, flesh_flavor, ",
        "flesh_scent, soluble_solid, ",
        "flesh_hardness, fruit_heart, ",
        "fruit_heart_shape, fruit_heart_num, ",
        "seed_size, seed_shape, ",
        "seed_num, seed_color, ",
        "fruit_quality)",
        "values (#{id,jdbcType=INTEGER}, #{germId,jdbcType=CHAR}, ",
        "#{sproutAbility,jdbcType=CHAR}, #{branchAbility,jdbcType=CHAR}, ",
        "#{branchAverLength,jdbcType=DECIMAL}, #{growtch,jdbcType=CHAR}, ",
        "#{firstFruitAge,jdbcType=INTEGER}, #{acmeFruitAge,jdbcType=INTEGER}, ",
        "#{longBranchRatio,jdbcType=DECIMAL}, #{midBranchRatio,jdbcType=DECIMAL}, ",
        "#{shortBranchRatio,jdbcType=DECIMAL}, #{axiBudRatio,jdbcType=DECIMAL}, ",
        "#{phyFruitDrop,jdbcType=CHAR}, #{beforeFruitDrop,jdbcType=CHAR}, ",
        "#{singleAverYield,jdbcType=DECIMAL}, #{singleMaxYield,jdbcType=DECIMAL}, ",
        "#{unitYield,jdbcType=DECIMAL}, #{yeildDescript,jdbcType=VARCHAR}, ",
        "#{germStage,jdbcType=VARCHAR}, #{flowerStage,jdbcType=VARCHAR}, ",
        "#{harvestStage,jdbcType=VARCHAR}, #{leaffallStage,jdbcType=VARCHAR}, ",
        "#{storage,jdbcType=INTEGER}, #{diseases,jdbcType=VARCHAR}, ",
        "#{pest,jdbcType=VARCHAR}, #{coldResistance,jdbcType=CHAR}, ",
        "#{drougthResistance,jdbcType=CHAR}, #{windResistance,jdbcType=CHAR}, ",
        "#{waterResistance,jdbcType=CHAR}, #{soilAdaptive,jdbcType=VARCHAR}, ",
        "#{climateAdaptive,jdbcType=VARCHAR}, #{plantingCondition,jdbcType=VARCHAR}, ",
        "#{fruitLongDiameter,jdbcType=DECIMAL}, #{fruitLatDiameter,jdbcType=DECIMAL}, ",
        "#{singleFruitWeight,jdbcType=DECIMAL}, #{fruitShape,jdbcType=VARCHAR}, ",
        "#{fruitColor,jdbcType=VARCHAR}, #{fruitSkin,jdbcType=VARCHAR}, ",
        "#{fruitWax,jdbcType=CHAR}, #{fruitDots,jdbcType=VARCHAR}, ",
        "#{fruitStem,jdbcType=VARCHAR}, #{fruitHollow,jdbcType=VARCHAR}, ",
        "#{fruitSepal,jdbcType=VARCHAR}, #{fruitDepression,jdbcType=VARCHAR}, ",
        "#{fleshColor,jdbcType=VARCHAR}, #{fleshTexture,jdbcType=CHAR}, ",
        "#{fleshType,jdbcType=VARCHAR}, #{fleshStoneCell,jdbcType=CHAR}, ",
        "#{fleshJuice,jdbcType=CHAR}, #{fleshFlavor,jdbcType=VARCHAR}, ",
        "#{fleshScent,jdbcType=VARCHAR}, #{solubleSolid,jdbcType=DECIMAL}, ",
        "#{fleshHardness,jdbcType=DECIMAL}, #{fruitHeart,jdbcType=CHAR}, ",
        "#{fruitHeartShape,jdbcType=VARCHAR}, #{fruitHeartNum,jdbcType=INTEGER}, ",
        "#{seedSize,jdbcType=VARCHAR}, #{seedShape,jdbcType=VARCHAR}, ",
        "#{seedNum,jdbcType=INTEGER}, #{seedColor,jdbcType=VARCHAR}, ",
        "#{fruitQuality,jdbcType=CHAR})"
    })
    int insert(BiologyInfo record);

    @InsertProvider(type=BiologyInfoSqlProvider.class, method="insertSelective")
    int insertSelective(BiologyInfo record);

    @Select({
        "select",
        "id, germ_id, sprout_ability, branch_ability, branch_aver_length, growtch, first_fruit_age, ",
        "acme_fruit_age, long_branch_ratio, mid_branch_ratio, short_branch_ratio, axi_bud_ratio, ",
        "phy_fruit_drop, before_fruit_drop, single_aver_yield, single_max_yield, unit_yield, ",
        "yeild_descript, germ_stage, flower_stage, harvest_stage, leaffall_stage, storage, ",
        "diseases, pest, cold_resistance, drougth_resistance, wind_resistance, water_resistance, ",
        "soil_adaptive, climate_adaptive, planting_condition, fruit_long_diameter, fruit_lat_diameter, ",
        "single_fruit_weight, fruit_shape, fruit_color, fruit_skin, fruit_wax, fruit_dots, ",
        "fruit_stem, fruit_hollow, fruit_sepal, fruit_depression, flesh_color, flesh_texture, ",
        "flesh_type, flesh_stone_cell, flesh_juice, flesh_flavor, flesh_scent, soluble_solid, ",
        "flesh_hardness, fruit_heart, fruit_heart_shape, fruit_heart_num, seed_size, ",
        "seed_shape, seed_num, seed_color, fruit_quality",
        "from biology_info",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="germ_id", property="germId", jdbcType=JdbcType.CHAR),
        @Result(column="sprout_ability", property="sproutAbility", jdbcType=JdbcType.CHAR),
        @Result(column="branch_ability", property="branchAbility", jdbcType=JdbcType.CHAR),
        @Result(column="branch_aver_length", property="branchAverLength", jdbcType=JdbcType.DECIMAL),
        @Result(column="growtch", property="growtch", jdbcType=JdbcType.CHAR),
        @Result(column="first_fruit_age", property="firstFruitAge", jdbcType=JdbcType.INTEGER),
        @Result(column="acme_fruit_age", property="acmeFruitAge", jdbcType=JdbcType.INTEGER),
        @Result(column="long_branch_ratio", property="longBranchRatio", jdbcType=JdbcType.DECIMAL),
        @Result(column="mid_branch_ratio", property="midBranchRatio", jdbcType=JdbcType.DECIMAL),
        @Result(column="short_branch_ratio", property="shortBranchRatio", jdbcType=JdbcType.DECIMAL),
        @Result(column="axi_bud_ratio", property="axiBudRatio", jdbcType=JdbcType.DECIMAL),
        @Result(column="phy_fruit_drop", property="phyFruitDrop", jdbcType=JdbcType.CHAR),
        @Result(column="before_fruit_drop", property="beforeFruitDrop", jdbcType=JdbcType.CHAR),
        @Result(column="single_aver_yield", property="singleAverYield", jdbcType=JdbcType.DECIMAL),
        @Result(column="single_max_yield", property="singleMaxYield", jdbcType=JdbcType.DECIMAL),
        @Result(column="unit_yield", property="unitYield", jdbcType=JdbcType.DECIMAL),
        @Result(column="yeild_descript", property="yeildDescript", jdbcType=JdbcType.VARCHAR),
        @Result(column="germ_stage", property="germStage", jdbcType=JdbcType.VARCHAR),
        @Result(column="flower_stage", property="flowerStage", jdbcType=JdbcType.VARCHAR),
        @Result(column="harvest_stage", property="harvestStage", jdbcType=JdbcType.VARCHAR),
        @Result(column="leaffall_stage", property="leaffallStage", jdbcType=JdbcType.VARCHAR),
        @Result(column="storage", property="storage", jdbcType=JdbcType.INTEGER),
        @Result(column="diseases", property="diseases", jdbcType=JdbcType.VARCHAR),
        @Result(column="pest", property="pest", jdbcType=JdbcType.VARCHAR),
        @Result(column="cold_resistance", property="coldResistance", jdbcType=JdbcType.CHAR),
        @Result(column="drougth_resistance", property="drougthResistance", jdbcType=JdbcType.CHAR),
        @Result(column="wind_resistance", property="windResistance", jdbcType=JdbcType.CHAR),
        @Result(column="water_resistance", property="waterResistance", jdbcType=JdbcType.CHAR),
        @Result(column="soil_adaptive", property="soilAdaptive", jdbcType=JdbcType.VARCHAR),
        @Result(column="climate_adaptive", property="climateAdaptive", jdbcType=JdbcType.VARCHAR),
        @Result(column="planting_condition", property="plantingCondition", jdbcType=JdbcType.VARCHAR),
        @Result(column="fruit_long_diameter", property="fruitLongDiameter", jdbcType=JdbcType.DECIMAL),
        @Result(column="fruit_lat_diameter", property="fruitLatDiameter", jdbcType=JdbcType.DECIMAL),
        @Result(column="single_fruit_weight", property="singleFruitWeight", jdbcType=JdbcType.DECIMAL),
        @Result(column="fruit_shape", property="fruitShape", jdbcType=JdbcType.VARCHAR),
        @Result(column="fruit_color", property="fruitColor", jdbcType=JdbcType.VARCHAR),
        @Result(column="fruit_skin", property="fruitSkin", jdbcType=JdbcType.VARCHAR),
        @Result(column="fruit_wax", property="fruitWax", jdbcType=JdbcType.CHAR),
        @Result(column="fruit_dots", property="fruitDots", jdbcType=JdbcType.VARCHAR),
        @Result(column="fruit_stem", property="fruitStem", jdbcType=JdbcType.VARCHAR),
        @Result(column="fruit_hollow", property="fruitHollow", jdbcType=JdbcType.VARCHAR),
        @Result(column="fruit_sepal", property="fruitSepal", jdbcType=JdbcType.VARCHAR),
        @Result(column="fruit_depression", property="fruitDepression", jdbcType=JdbcType.VARCHAR),
        @Result(column="flesh_color", property="fleshColor", jdbcType=JdbcType.VARCHAR),
        @Result(column="flesh_texture", property="fleshTexture", jdbcType=JdbcType.CHAR),
        @Result(column="flesh_type", property="fleshType", jdbcType=JdbcType.VARCHAR),
        @Result(column="flesh_stone_cell", property="fleshStoneCell", jdbcType=JdbcType.CHAR),
        @Result(column="flesh_juice", property="fleshJuice", jdbcType=JdbcType.CHAR),
        @Result(column="flesh_flavor", property="fleshFlavor", jdbcType=JdbcType.VARCHAR),
        @Result(column="flesh_scent", property="fleshScent", jdbcType=JdbcType.VARCHAR),
        @Result(column="soluble_solid", property="solubleSolid", jdbcType=JdbcType.DECIMAL),
        @Result(column="flesh_hardness", property="fleshHardness", jdbcType=JdbcType.DECIMAL),
        @Result(column="fruit_heart", property="fruitHeart", jdbcType=JdbcType.CHAR),
        @Result(column="fruit_heart_shape", property="fruitHeartShape", jdbcType=JdbcType.VARCHAR),
        @Result(column="fruit_heart_num", property="fruitHeartNum", jdbcType=JdbcType.INTEGER),
        @Result(column="seed_size", property="seedSize", jdbcType=JdbcType.VARCHAR),
        @Result(column="seed_shape", property="seedShape", jdbcType=JdbcType.VARCHAR),
        @Result(column="seed_num", property="seedNum", jdbcType=JdbcType.INTEGER),
        @Result(column="seed_color", property="seedColor", jdbcType=JdbcType.VARCHAR),
        @Result(column="fruit_quality", property="fruitQuality", jdbcType=JdbcType.CHAR)
    })
    BiologyInfo selectByPrimaryKey(Integer id);

    @UpdateProvider(type=BiologyInfoSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(BiologyInfo record);

    @Update({
        "update biology_info",
        "set germ_id = #{germId,jdbcType=CHAR},",
          "sprout_ability = #{sproutAbility,jdbcType=CHAR},",
          "branch_ability = #{branchAbility,jdbcType=CHAR},",
          "branch_aver_length = #{branchAverLength,jdbcType=DECIMAL},",
          "growtch = #{growtch,jdbcType=CHAR},",
          "first_fruit_age = #{firstFruitAge,jdbcType=INTEGER},",
          "acme_fruit_age = #{acmeFruitAge,jdbcType=INTEGER},",
          "long_branch_ratio = #{longBranchRatio,jdbcType=DECIMAL},",
          "mid_branch_ratio = #{midBranchRatio,jdbcType=DECIMAL},",
          "short_branch_ratio = #{shortBranchRatio,jdbcType=DECIMAL},",
          "axi_bud_ratio = #{axiBudRatio,jdbcType=DECIMAL},",
          "phy_fruit_drop = #{phyFruitDrop,jdbcType=CHAR},",
          "before_fruit_drop = #{beforeFruitDrop,jdbcType=CHAR},",
          "single_aver_yield = #{singleAverYield,jdbcType=DECIMAL},",
          "single_max_yield = #{singleMaxYield,jdbcType=DECIMAL},",
          "unit_yield = #{unitYield,jdbcType=DECIMAL},",
          "yeild_descript = #{yeildDescript,jdbcType=VARCHAR},",
          "germ_stage = #{germStage,jdbcType=VARCHAR},",
          "flower_stage = #{flowerStage,jdbcType=VARCHAR},",
          "harvest_stage = #{harvestStage,jdbcType=VARCHAR},",
          "leaffall_stage = #{leaffallStage,jdbcType=VARCHAR},",
          "storage = #{storage,jdbcType=INTEGER},",
          "diseases = #{diseases,jdbcType=VARCHAR},",
          "pest = #{pest,jdbcType=VARCHAR},",
          "cold_resistance = #{coldResistance,jdbcType=CHAR},",
          "drougth_resistance = #{drougthResistance,jdbcType=CHAR},",
          "wind_resistance = #{windResistance,jdbcType=CHAR},",
          "water_resistance = #{waterResistance,jdbcType=CHAR},",
          "soil_adaptive = #{soilAdaptive,jdbcType=VARCHAR},",
          "climate_adaptive = #{climateAdaptive,jdbcType=VARCHAR},",
          "planting_condition = #{plantingCondition,jdbcType=VARCHAR},",
          "fruit_long_diameter = #{fruitLongDiameter,jdbcType=DECIMAL},",
          "fruit_lat_diameter = #{fruitLatDiameter,jdbcType=DECIMAL},",
          "single_fruit_weight = #{singleFruitWeight,jdbcType=DECIMAL},",
          "fruit_shape = #{fruitShape,jdbcType=VARCHAR},",
          "fruit_color = #{fruitColor,jdbcType=VARCHAR},",
          "fruit_skin = #{fruitSkin,jdbcType=VARCHAR},",
          "fruit_wax = #{fruitWax,jdbcType=CHAR},",
          "fruit_dots = #{fruitDots,jdbcType=VARCHAR},",
          "fruit_stem = #{fruitStem,jdbcType=VARCHAR},",
          "fruit_hollow = #{fruitHollow,jdbcType=VARCHAR},",
          "fruit_sepal = #{fruitSepal,jdbcType=VARCHAR},",
          "fruit_depression = #{fruitDepression,jdbcType=VARCHAR},",
          "flesh_color = #{fleshColor,jdbcType=VARCHAR},",
          "flesh_texture = #{fleshTexture,jdbcType=CHAR},",
          "flesh_type = #{fleshType,jdbcType=VARCHAR},",
          "flesh_stone_cell = #{fleshStoneCell,jdbcType=CHAR},",
          "flesh_juice = #{fleshJuice,jdbcType=CHAR},",
          "flesh_flavor = #{fleshFlavor,jdbcType=VARCHAR},",
          "flesh_scent = #{fleshScent,jdbcType=VARCHAR},",
          "soluble_solid = #{solubleSolid,jdbcType=DECIMAL},",
          "flesh_hardness = #{fleshHardness,jdbcType=DECIMAL},",
          "fruit_heart = #{fruitHeart,jdbcType=CHAR},",
          "fruit_heart_shape = #{fruitHeartShape,jdbcType=VARCHAR},",
          "fruit_heart_num = #{fruitHeartNum,jdbcType=INTEGER},",
          "seed_size = #{seedSize,jdbcType=VARCHAR},",
          "seed_shape = #{seedShape,jdbcType=VARCHAR},",
          "seed_num = #{seedNum,jdbcType=INTEGER},",
          "seed_color = #{seedColor,jdbcType=VARCHAR},",
          "fruit_quality = #{fruitQuality,jdbcType=CHAR}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(BiologyInfo record);
}